version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Or "frontend", "backend", etc.
    schedule:
      interval: "daily" # Valid values: daily, weekly, monthly, etc.

  - package-ecosystem: "github-actions"
    directory: "/" # Always root
    schedule:
      interval: "immediately"
