name: Configure CNAME

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  cname:
    runs-on: - ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CNAME
        run: |
          echo "elparadisogonzalo.net" > CNAME

      - name: Commit CNAME
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "299702475+azehagowa1@users.noreply.github.com"
          git add CNAME

          if git diff --cached --quiet; then
            echo "CNAME already up to date."
          else
            git commit -m "chore: configure custom domain"
            git push
          fi
